// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/r3st/turnscore/internal/domain (interfaces: TableRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/mocks/mock_table_repo.go -package=mocks github.com/r3st/turnscore/internal/domain TableRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/r3st/turnscore/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTableRepository is a mock of TableRepository interface.
type MockTableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTableRepositoryMockRecorder
	isgomock struct{}
}

// MockTableRepositoryMockRecorder is the mock recorder for MockTableRepository.
type MockTableRepositoryMockRecorder struct {
	mock *MockTableRepository
}

// NewMockTableRepository creates a new mock instance.
func NewMockTableRepository(ctrl *gomock.Controller) *MockTableRepository {
	mock := &MockTableRepository{ctrl: ctrl}
	mock.recorder = &MockTableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableRepository) EXPECT() *MockTableRepositoryMockRecorder {
	return m.recorder
}

// CountByTournamentID mocks base method.
func (m *MockTableRepository) CountByTournamentID(ctx context.Context, tournamentID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTournamentID", ctx, tournamentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTournamentID indicates an expected call of CountByTournamentID.
func (mr *MockTableRepositoryMockRecorder) CountByTournamentID(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTournamentID", reflect.TypeOf((*MockTableRepository)(nil).CountByTournamentID), ctx, tournamentID)
}

// CreateBatch mocks base method.
func (m *MockTableRepository) CreateBatch(ctx context.Context, tables []domain.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, tables)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockTableRepositoryMockRecorder) CreateBatch(ctx, tables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockTableRepository)(nil).CreateBatch), ctx, tables)
}

// FindByID mocks base method.
func (m *MockTableRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTableRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTableRepository)(nil).FindByID), ctx, id)
}

// FindByTournamentAndNumber mocks base method.
func (m *MockTableRepository) FindByTournamentAndNumber(ctx context.Context, tournamentID uuid.UUID, number int) (*domain.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTournamentAndNumber", ctx, tournamentID, number)
	ret0, _ := ret[0].(*domain.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTournamentAndNumber indicates an expected call of FindByTournamentAndNumber.
func (mr *MockTableRepositoryMockRecorder) FindByTournamentAndNumber(ctx, tournamentID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTournamentAndNumber", reflect.TypeOf((*MockTableRepository)(nil).FindByTournamentAndNumber), ctx, tournamentID, number)
}

// ListByTournamentID mocks base method.
func (m *MockTableRepository) ListByTournamentID(ctx context.Context, tournamentID uuid.UUID) ([]domain.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTournamentID", ctx, tournamentID)
	ret0, _ := ret[0].([]domain.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTournamentID indicates an expected call of ListByTournamentID.
func (mr *MockTableRepositoryMockRecorder) ListByTournamentID(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTournamentID", reflect.TypeOf((*MockTableRepository)(nil).ListByTournamentID), ctx, tournamentID)
}

// Update mocks base method.
func (m *MockTableRepository) Update(ctx context.Context, t *domain.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTableRepositoryMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTableRepository)(nil).Update), ctx, t)
}

// UpdateQRCodePath mocks base method.
func (m *MockTableRepository) UpdateQRCodePath(ctx context.Context, tableID uuid.UUID, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQRCodePath", ctx, tableID, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQRCodePath indicates an expected call of UpdateQRCodePath.
func (mr *MockTableRepositoryMockRecorder) UpdateQRCodePath(ctx, tableID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQRCodePath", reflect.TypeOf((*MockTableRepository)(nil).UpdateQRCodePath), ctx, tableID, path)
}
