// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/r3st/turnscore/internal/domain (interfaces: RaterRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/mocks/mock_rater_repo.go -package=mocks github.com/r3st/turnscore/internal/domain RaterRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/r3st/turnscore/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRaterRepository is a mock of RaterRepository interface.
type MockRaterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRaterRepositoryMockRecorder
	isgomock struct{}
}

// MockRaterRepositoryMockRecorder is the mock recorder for MockRaterRepository.
type MockRaterRepositoryMockRecorder struct {
	mock *MockRaterRepository
}

// NewMockRaterRepository creates a new mock instance.
func NewMockRaterRepository(ctrl *gomock.Controller) *MockRaterRepository {
	mock := &MockRaterRepository{ctrl: ctrl}
	mock.recorder = &MockRaterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaterRepository) EXPECT() *MockRaterRepositoryMockRecorder {
	return m.recorder
}

// FindByNicknameAndCode mocks base method.
func (m *MockRaterRepository) FindByNicknameAndCode(ctx any, tournamentID uuid.UUID, nickname, code string) (*domain.Rater, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNicknameAndCode", ctx, tournamentID, nickname, code)
	ret0, _ := ret[0].(*domain.Rater)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNicknameAndCode indicates an expected call of FindByNicknameAndCode.
func (mr *MockRaterRepositoryMockRecorder) FindByNicknameAndCode(ctx, tournamentID, nickname, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNicknameAndCode", reflect.TypeOf((*MockRaterRepository)(nil).FindByNicknameAndCode), ctx, tournamentID, nickname, code)
}
