// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/r3st/turnscore/internal/domain (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/mocks/mock_user_repo.go -package=mocks github.com/r3st/turnscore/internal/domain UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/r3st/turnscore/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// DeleteRefreshToken mocks base method.
func (m *MockUserRepository) DeleteRefreshToken(ctx any, hashedToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, hashedToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockUserRepositoryMockRecorder) DeleteRefreshToken(ctx, hashedToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockUserRepository)(nil).DeleteRefreshToken), ctx, hashedToken)
}

// FindByHelperInviteCode mocks base method.
func (m *MockUserRepository) FindByHelperInviteCode(ctx any, code string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHelperInviteCode", ctx, code)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHelperInviteCode indicates an expected call of FindByHelperInviteCode.
func (mr *MockUserRepositoryMockRecorder) FindByHelperInviteCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHelperInviteCode", reflect.TypeOf((*MockUserRepository)(nil).FindByHelperInviteCode), ctx, code)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx any, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// FindByRefreshToken mocks base method.
func (m *MockUserRepository) FindByRefreshToken(ctx any, token string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRefreshToken", ctx, token)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRefreshToken indicates an expected call of FindByRefreshToken.
func (mr *MockUserRepositoryMockRecorder) FindByRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRefreshToken", reflect.TypeOf((*MockUserRepository)(nil).FindByRefreshToken), ctx, token)
}

// SaveRefreshToken mocks base method.
func (m *MockUserRepository) SaveRefreshToken(ctx any, userID uuid.UUID, hashedToken string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, userID, hashedToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockUserRepositoryMockRecorder) SaveRefreshToken(ctx, userID, hashedToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockUserRepository)(nil).SaveRefreshToken), ctx, userID, hashedToken, expiresAt)
}

// UpdatePreferences mocks base method.
func (m *MockUserRepository) UpdatePreferences(ctx any, userID uuid.UUID, input domain.UpdatePreferencesInput) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreferences", ctx, userID, input)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePreferences indicates an expected call of UpdatePreferences.
func (mr *MockUserRepositoryMockRecorder) UpdatePreferences(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferences", reflect.TypeOf((*MockUserRepository)(nil).UpdatePreferences), ctx, userID, input)
}

// UpsertByGoogleSub mocks base method.
func (m *MockUserRepository) UpsertByGoogleSub(ctx any, googleSub, email, name, avatarURL string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertByGoogleSub", ctx, googleSub, email, name, avatarURL)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertByGoogleSub indicates an expected call of UpsertByGoogleSub.
func (mr *MockUserRepositoryMockRecorder) UpsertByGoogleSub(ctx, googleSub, email, name, avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByGoogleSub", reflect.TypeOf((*MockUserRepository)(nil).UpsertByGoogleSub), ctx, googleSub, email, name, avatarURL)
}
