// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/r3st/turnscore/internal/domain (interfaces: TournamentMemberRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/mocks/mock_tournament_member_repo.go -package=mocks github.com/r3st/turnscore/internal/domain TournamentMemberRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTournamentMemberRepository is a mock of TournamentMemberRepository interface.
type MockTournamentMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockTournamentMemberRepositoryMockRecorder is the mock recorder for MockTournamentMemberRepository.
type MockTournamentMemberRepositoryMockRecorder struct {
	mock *MockTournamentMemberRepository
}

// NewMockTournamentMemberRepository creates a new mock instance.
func NewMockTournamentMemberRepository(ctrl *gomock.Controller) *MockTournamentMemberRepository {
	mock := &MockTournamentMemberRepository{ctrl: ctrl}
	mock.recorder = &MockTournamentMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentMemberRepository) EXPECT() *MockTournamentMemberRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockTournamentMemberRepository) AddMember(ctx context.Context, tournamentID, userID uuid.UUID, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, tournamentID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockTournamentMemberRepositoryMockRecorder) AddMember(ctx, tournamentID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockTournamentMemberRepository)(nil).AddMember), ctx, tournamentID, userID, role)
}

// GetRole mocks base method.
func (m *MockTournamentMemberRepository) GetRole(ctx context.Context, tournamentID, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, tournamentID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockTournamentMemberRepositoryMockRecorder) GetRole(ctx, tournamentID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockTournamentMemberRepository)(nil).GetRole), ctx, tournamentID, userID)
}

// RemoveMember mocks base method.
func (m *MockTournamentMemberRepository) RemoveMember(ctx context.Context, tournamentID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, tournamentID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTournamentMemberRepositoryMockRecorder) RemoveMember(ctx, tournamentID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTournamentMemberRepository)(nil).RemoveMember), ctx, tournamentID, userID)
}
