// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/r3st/turnscore/internal/domain (interfaces: EventRatingRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/mocks/mock_event_rating_repo.go -package=mocks github.com/r3st/turnscore/internal/domain EventRatingRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/r3st/turnscore/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRatingRepository is a mock of EventRatingRepository interface.
type MockEventRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRatingRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRatingRepositoryMockRecorder is the mock recorder for MockEventRatingRepository.
type MockEventRatingRepositoryMockRecorder struct {
	mock *MockEventRatingRepository
}

// NewMockEventRatingRepository creates a new mock instance.
func NewMockEventRatingRepository(ctrl *gomock.Controller) *MockEventRatingRepository {
	mock := &MockEventRatingRepository{ctrl: ctrl}
	mock.recorder = &MockEventRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRatingRepository) EXPECT() *MockEventRatingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventRatingRepository) Create(ctx context.Context, r *domain.EventRating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventRatingRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRatingRepository)(nil).Create), ctx, r)
}

// GetAveragesForTournament mocks base method.
func (m *MockEventRatingRepository) GetAveragesForTournament(ctx context.Context, tournamentID uuid.UUID) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAveragesForTournament", ctx, tournamentID)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAveragesForTournament indicates an expected call of GetAveragesForTournament.
func (mr *MockEventRatingRepositoryMockRecorder) GetAveragesForTournament(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAveragesForTournament", reflect.TypeOf((*MockEventRatingRepository)(nil).GetAveragesForTournament), ctx, tournamentID)
}

// ExistsByTournamentAndRater mocks base method.
func (m *MockEventRatingRepository) ExistsByTournamentAndRater(ctx context.Context, tournamentID, raterID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByTournamentAndRater", ctx, tournamentID, raterID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByTournamentAndRater indicates an expected call of ExistsByTournamentAndRater.
func (mr *MockEventRatingRepositoryMockRecorder) ExistsByTournamentAndRater(ctx, tournamentID, raterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByTournamentAndRater", reflect.TypeOf((*MockEventRatingRepository)(nil).ExistsByTournamentAndRater), ctx, tournamentID, raterID)
}
