// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/r3st/turnscore/internal/domain (interfaces: RatingRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/mocks/mock_rating_repo.go -package=mocks github.com/r3st/turnscore/internal/domain RatingRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/r3st/turnscore/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingRepository is a mock of RatingRepository interface.
type MockRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepositoryMockRecorder
	isgomock struct{}
}

// MockRatingRepositoryMockRecorder is the mock recorder for MockRatingRepository.
type MockRatingRepositoryMockRecorder struct {
	mock *MockRatingRepository
}

// NewMockRatingRepository creates a new mock instance.
func NewMockRatingRepository(ctrl *gomock.Controller) *MockRatingRepository {
	mock := &MockRatingRepository{ctrl: ctrl}
	mock.recorder = &MockRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepository) EXPECT() *MockRatingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRatingRepository) Create(ctx context.Context, r *domain.Rating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRatingRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRatingRepository)(nil).Create), ctx, r)
}

// ExistsByTableAndRater mocks base method.
func (m *MockRatingRepository) ExistsByTableAndRater(ctx context.Context, tableID, raterID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByTableAndRater", ctx, tableID, raterID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByTableAndRater indicates an expected call of ExistsByTableAndRater.
func (mr *MockRatingRepositoryMockRecorder) ExistsByTableAndRater(ctx, tableID, raterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByTableAndRater", reflect.TypeOf((*MockRatingRepository)(nil).ExistsByTableAndRater), ctx, tableID, raterID)
}

// GetCommentsForTournament mocks base method.
func (m *MockRatingRepository) GetCommentsForTournament(ctx context.Context, tournamentID uuid.UUID) (map[uuid.UUID][]domain.CommentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsForTournament", ctx, tournamentID)
	ret0, _ := ret[0].(map[uuid.UUID][]domain.CommentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsForTournament indicates an expected call of GetCommentsForTournament.
func (mr *MockRatingRepositoryMockRecorder) GetCommentsForTournament(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsForTournament", reflect.TypeOf((*MockRatingRepository)(nil).GetCommentsForTournament), ctx, tournamentID)
}

// SetCommentApproved mocks base method.
func (m *MockRatingRepository) SetCommentApproved(ctx context.Context, ratingID uuid.UUID, approved bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommentApproved", ctx, ratingID, approved)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCommentApproved indicates an expected call of SetCommentApproved.
func (mr *MockRatingRepositoryMockRecorder) SetCommentApproved(ctx, ratingID, approved any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommentApproved", reflect.TypeOf((*MockRatingRepository)(nil).SetCommentApproved), ctx, ratingID, approved)
}

// GetRatedTableNumbers mocks base method.
func (m *MockRatingRepository) GetRatedTableNumbers(ctx context.Context, tournamentID, raterID uuid.UUID) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatedTableNumbers", ctx, tournamentID, raterID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatedTableNumbers indicates an expected call of GetRatedTableNumbers.
func (mr *MockRatingRepositoryMockRecorder) GetRatedTableNumbers(ctx, tournamentID, raterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatedTableNumbers", reflect.TypeOf((*MockRatingRepository)(nil).GetRatedTableNumbers), ctx, tournamentID, raterID)
}

// GetResultsForTournament mocks base method.
func (m *MockRatingRepository) GetResultsForTournament(ctx context.Context, tournamentID uuid.UUID) ([]domain.RatingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResultsForTournament", ctx, tournamentID)
	ret0, _ := ret[0].([]domain.RatingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResultsForTournament indicates an expected call of GetResultsForTournament.
func (mr *MockRatingRepositoryMockRecorder) GetResultsForTournament(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResultsForTournament", reflect.TypeOf((*MockRatingRepository)(nil).GetResultsForTournament), ctx, tournamentID)
}
