// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/r3st/turnscore/internal/domain (interfaces: PhotoRepository)
//
// Generated by this command:
//
//	mockgen -destination=pkg/mocks/mock_photo_repo.go -package=mocks github.com/r3st/turnscore/internal/domain PhotoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/r3st/turnscore/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPhotoRepository is a mock of PhotoRepository interface.
type MockPhotoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoRepositoryMockRecorder
	isgomock struct{}
}

// MockPhotoRepositoryMockRecorder is the mock recorder for MockPhotoRepository.
type MockPhotoRepositoryMockRecorder struct {
	mock *MockPhotoRepository
}

// NewMockPhotoRepository creates a new mock instance.
func NewMockPhotoRepository(ctrl *gomock.Controller) *MockPhotoRepository {
	mock := &MockPhotoRepository{ctrl: ctrl}
	mock.recorder = &MockPhotoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoRepository) EXPECT() *MockPhotoRepositoryMockRecorder {
	return m.recorder
}

// BelongsToTournament mocks base method.
func (m *MockPhotoRepository) BelongsToTournament(ctx context.Context, photoID, tournamentID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BelongsToTournament", ctx, photoID, tournamentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BelongsToTournament indicates an expected call of BelongsToTournament.
func (mr *MockPhotoRepositoryMockRecorder) BelongsToTournament(ctx, photoID, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BelongsToTournament", reflect.TypeOf((*MockPhotoRepository)(nil).BelongsToTournament), ctx, photoID, tournamentID)
}

// Create mocks base method.
func (m *MockPhotoRepository) Create(ctx context.Context, p *domain.Photo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPhotoRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPhotoRepository)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockPhotoRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPhotoRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPhotoRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockPhotoRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPhotoRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPhotoRepository)(nil).FindByID), ctx, id)
}

// FindByTableID mocks base method.
func (m *MockPhotoRepository) FindByTableID(ctx context.Context, tableID uuid.UUID) ([]domain.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTableID", ctx, tableID)
	ret0, _ := ret[0].([]domain.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTableID indicates an expected call of FindByTableID.
func (mr *MockPhotoRepositoryMockRecorder) FindByTableID(ctx, tableID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTableID", reflect.TypeOf((*MockPhotoRepository)(nil).FindByTableID), ctx, tableID)
}
